export default {
  configs: [
    {
      'code': 'und',
      'en': 'Detect Language',
      'zh_Hans': '检测语言',
      'zh_Hant': '檢測語言',
      'es': 'Detectar Idioma',
      'fr': 'Détecter la Langue',
      'pt': 'Detectar Idioma',
      'ru': 'Определить Язык',
      'de': 'Sprache Erkennen',
      'ja': '言語を検出',
      'it': 'Rileva Lingua',
      'ko': '언어 감지',
      'ar': 'كشف اللغة'
    },
    {
      'code': 'ar',
      'en': 'Arabic',
      'zh_Hans': '阿拉伯语',
      'zh_Hant': '阿拉伯語',
      'es': 'Árabe',
      'fr': 'Arabe',
      'pt': 'Árabe',
      'ru': 'Арабский',
      'de': 'Arabisch',
      'ja': 'アラビア語',
      'it': 'Arabo',
      'ko': '아랍어',
      'ar': 'العربية'
    },
    {
      'code': 'bg',
      'en': 'Bulgarian',
      'zh_Hans': '保加利亚语',
      'zh_Hant': '保加利亞語',
      'es': 'Búlgaro',
      'fr': 'Bulgare',
      'pt': 'Búlgaro',
      'ru': 'Болгарский',
      'de': 'Bulgarisch',
      'ja': 'ブルガリア語',
      'it': 'Bulgaro',
      'ko': '불가리아어',
      'ar': 'البلغارية'
    },
    {
      'code': 'bn',
      'en': 'Bengali',
      'zh_Hans': '孟加拉语',
      'zh_Hant': '孟加拉語',
      'es': 'Bengalí',
      'fr': 'Bengali',
      'pt': 'Bengali',
      'ru': 'Бенгальский',
      'de': 'Bengalisch',
      'ja': 'ベンガル語',
      'it': 'Bengalese',
      'ko': '벵골어',
      'ar': 'البنغالية'
    },
    {
      'code': 'cs',
      'en': 'Czech',
      'zh_Hans': '捷克语',
      'zh_Hant': '捷克語',
      'es': 'Checo',
      'fr': 'Tchèque',
      'pt': 'Tcheco',
      'ru': 'Чешский',
      'de': 'Tschechisch',
      'ja': 'チェコ語',
      'it': 'Ceco',
      'ko': '체코어',
      'ar': 'التشيكية'
    },
    {
      'code': 'da',
      'en': 'Danish',
      'zh_Hans': '丹麦语',
      'zh_Hant': '丹麥語',
      'es': 'Danés',
      'fr': 'Danois',
      'pt': 'Dinamarquês',
      'ru': 'Датский',
      'de': 'Dänisch',
      'ja': 'デンマーク語',
      'it': 'Danese',
      'ko': '덴마크어',
      'ar': 'الدانماركية'
    },
    {
      'code': 'de',
      'en': 'German',
      'zh_Hans': '德语',
      'zh_Hant': '德語',
      'es': 'Alemán',
      'fr': 'Allemand',
      'pt': 'Alemão',
      'ru': 'Немецкий',
      'de': 'Deutsch',
      'ja': 'ドイツ語',
      'it': 'Tedesco',
      'ko': '독일어',
      'ar': 'الألمانية'
    },
    {
      'code': 'el',
      'en': 'Greek',
      'zh_Hans': '希腊语',
      'zh_Hant': '希臘語',
      'es': 'Griego',
      'fr': 'Grec',
      'pt': 'Grego',
      'ru': 'Греческий',
      'de': 'Griechisch',
      'ja': 'ギリシャ語',
      'it': 'Greco',
      'ko': '그리스어',
      'ar': 'اليونانية'
    },
    {
      'code': 'en',
      'en': 'English',
      'zh_Hans': '英语',
      'zh_Hant': '英語',
      'es': 'Inglés',
      'fr': 'Anglais',
      'pt': 'Inglês',
      'ru': 'Английский',
      'de': 'Englisch',
      'ja': '英語',
      'it': 'Inglese',
      'ko': '영어',
      'ar': 'الإنجليزية'
    },
    {
      'code': 'es',
      'en': 'Spanish',
      'zh_Hans': '西班牙语',
      'zh_Hant': '西班牙語',
      'es': 'Español',
      'fr': 'Espagnol',
      'pt': 'Espanhol',
      'ru': 'Испанский',
      'de': 'Spanisch',
      'ja': 'スペイン語',
      'it': 'Spagnolo',
      'ko': '스페인어',
      'ar': 'الإسبانية'
    },
    {
      'code': 'et',
      'en': 'Estonian',
      'zh_Hans': '爱沙尼亚语',
      'zh_Hant': '愛沙尼亞語',
      'es': 'Estonio',
      'fr': 'Estonien',
      'pt': 'Estoniano',
      'ru': 'Эстонский',
      'de': 'Estnisch',
      'ja': 'エストニア語',
      'it': 'Estone',
      'ko': '에스토니아어',
      'ar': 'الإستونية'
    },
    {
      'code': 'fi',
      'en': 'Finnish',
      'zh_Hans': '芬兰语',
      'zh_Hant': '芬蘭語',
      'es': 'Finlandés',
      'fr': 'Finnois',
      'pt': 'Finlandês',
      'ru': 'Финский',
      'de': 'Finnisch',
      'ja': 'フィンランド語',
      'it': 'Finlandese',
      'ko': '핀란드어',
      'ar': 'الفنلندية'
    },
    {
      'code': 'fr',
      'en': 'French',
      'zh_Hans': '法语',
      'zh_Hant': '法語',
      'es': 'Francés',
      'fr': 'Français',
      'pt': 'Francês',
      'ru': 'Французский',
      'de': 'Französisch',
      'ja': 'フランス語',
      'it': 'Francese',
      'ko': '프랑스어',
      'ar': 'الفرنسية'
    },
    {
      'code': 'hi',
      'en': 'Hindi',
      'zh_Hans': '印地语',
      'zh_Hant': '印地語',
      'es': 'Hindi',
      'fr': 'Hindi',
      'pt': 'Hindi',
      'ru': 'Хинди',
      'de': 'Hindi',
      'ja': 'ヒンディー語',
      'it': 'Hindi',
      'ko': '힌디어',
      'ar': 'الهندية'
    },
    {
      'code': 'hr',
      'en': 'Croatian',
      'zh_Hans': '克罗地亚语',
      'zh_Hant': '克羅地亞語',
      'es': 'Croata',
      'fr': 'Croate',
      'pt': 'Croata',
      'ru': 'Хорватский',
      'de': 'Kroatisch',
      'ja': 'クロアチア語',
      'it': 'Croato',
      'ko': '크로아티아어',
      'ar': 'الكرواتية'
    },
    {
      'code': 'hu',
      'en': 'Hungarian',
      'zh_Hans': '匈牙利语',
      'zh_Hant': '匈牙利語',
      'es': 'Húngaro',
      'fr': 'Hongrois',
      'pt': 'Húngaro',
      'ru': 'Венгерский',
      'de': 'Ungarisch',
      'ja': 'ハンガリー語',
      'it': 'Ungherese',
      'ko': '헝가리어',
      'ar': 'الهنغارية'
    },
    {
      'code': 'id',
      'en': 'Indonesian',
      'zh_Hans': '印度尼西亚语',
      'zh_Hant': '印度尼西亞語',
      'es': 'Indonesio',
      'fr': 'Indonésien',
      'pt': 'Indonésio',
      'ru': 'Индонезийский',
      'de': 'Indonesisch',
      'ja': 'インドネシア語',
      'it': 'Indonesiano',
      'ko': '인도네시아어',
      'ar': 'الإندونيسية'
    },
    {
      'code': 'it',
      'en': 'Italian',
      'zh_Hans': '意大利语',
      'zh_Hant': '義大利語',
      'es': 'Italiano',
      'fr': 'Italien',
      'pt': 'Italiano',
      'ru': 'Итальянский',
      'de': 'Italienisch',
      'ja': 'イタリア語',
      'it': 'Italiano',
      'ko': '이탈리아어',
      'ar': 'الإيطالية'
    },
    {
      'code': 'iw',
      'en': 'Hebrew',
      'zh_Hans': '希伯来语',
      'zh_Hant': '希伯來語',
      'es': 'Hebreo',
      'fr': 'Hébreu',
      'pt': 'Hebraico',
      'ru': 'Иврит',
      'de': 'Hebräisch',
      'ja': 'ヘブライ語',
      'it': 'Ebraico',
      'ko': '히브리어',
      'ar': 'العبرية'
    },
    {
      'code': 'ja',
      'en': 'Japanese',
      'zh_Hans': '日语',
      'zh_Hant': '日語',
      'es': 'Japonés',
      'fr': 'Japonais',
      'pt': 'Japonês',
      'ru': 'Японский',
      'de': 'Japanisch',
      'ja': '日本語',
      'it': 'Giapponese',
      'ko': '일본어',
      'ar': 'اليابانية'
    },
    {
      'code': 'ko',
      'en': 'Korean',
      'zh_Hans': '韩语',
      'zh_Hant': '韓語',
      'es': 'Coreano',
      'fr': 'Coréen',
      'pt': 'Coreano',
      'ru': 'Корейский',
      'de': 'Koreanisch',
      'ja': '韓国語',
      'it': 'Coreano',
      'ko': '한국어',
      'ar': 'الكورية'
    },
    {
      'code': 'lt',
      'en': 'Lithuanian',
      'zh_Hans': '立陶宛语',
      'zh_Hant': '立陶宛語',
      'es': 'Lituano',
      'fr': 'Lituanien',
      'pt': 'Lituano',
      'ru': 'Литовский',
      'de': 'Litauisch',
      'ja': 'リトアニア語',
      'it': 'Lituano',
      'ko': '리투아니아어',
      'ar': 'الليتوانية'
    },
    {
      'code': 'lv',
      'en': 'Latvian',
      'zh_Hans': '拉脱维亚语',
      'zh_Hant': '拉脫維亞語',
      'es': 'Letón',
      'fr': 'Letton',
      'pt': 'Letão',
      'ru': 'Латышский',
      'de': 'Lettisch',
      'ja': 'ラトビア語',
      'it': 'Lettone',
      'ko': '라트비아어',
      'ar': 'اللاتفية'
    },
    {
      'code': 'nl',
      'en': 'Dutch',
      'zh_Hans': '荷兰语',
      'zh_Hant': '荷蘭語',
      'es': 'Neerlandés',
      'fr': 'Néerlandais',
      'pt': 'Holandês',
      'ru': 'Голландский',
      'de': 'Niederländisch',
      'ja': 'オランダ語',
      'it': 'Olandese',
      'ko': '네덜란드어',
      'ar': 'الهولندية'
    },
    {
      'code': 'no',
      'en': 'Norwegian',
      'zh_Hans': '挪威语',
      'zh_Hant': '挪威語',
      'es': 'Noruego',
      'fr': 'Norvégien',
      'pt': 'Norueguês',
      'ru': 'Норвежский',
      'de': 'Norwegisch',
      'ja': 'ノルウェー語',
      'it': 'Norvegese',
      'ko': '노르웨이어',
      'ar': 'النرويجية'
    },
    {
      'code': 'pl',
      'en': 'Polish',
      'zh_Hans': '波兰语',
      'zh_Hant': '波蘭語',
      'es': 'Polaco',
      'fr': 'Polonais',
      'pt': 'Polonês',
      'ru': 'Польский',
      'de': 'Polnisch',
      'ja': 'ポーランド語',
      'it': 'Polacco',
      'ko': '폴란드어',
      'ar': 'البولندية'
    },
    {
      'code': 'pt',
      'en': 'Portuguese',
      'zh_Hans': '葡萄牙语',
      'zh_Hant': '葡萄牙語',
      'es': 'Portugués',
      'fr': 'Portugais',
      'pt': 'Português',
      'ru': 'Португальский',
      'de': 'Portugiesisch',
      'ja': 'ポルトガル語',
      'it': 'Portoghese',
      'ko': '포르투갈어',
      'ar': 'البرتغالية'
    },
    {
      'code': 'ro',
      'en': 'Romanian',
      'zh_Hans': '罗马尼亚语',
      'zh_Hant': '羅馬尼亞語',
      'es': 'Rumano',
      'fr': 'Roumain',
      'pt': 'Romeno',
      'ru': 'Румынский',
      'de': 'Rumänisch',
      'ja': 'ルーマニア語',
      'it': 'Rumeno',
      'ko': '루마니아어',
      'ar': 'الرومانية'
    },
    {
      'code': 'ru',
      'en': 'Russian',
      'zh_Hans': '俄语',
      'zh_Hant': '俄語',
      'es': 'Ruso',
      'fr': 'Russe',
      'pt': 'Russo',
      'ru': 'Русский',
      'de': 'Russisch',
      'ja': 'ロシア語',
      'it': 'Russo',
      'ko': '러시아어',
      'ar': 'الروسية'
    },
    {
      'code': 'sk',
      'en': 'Slovak',
      'zh_Hans': '斯洛伐克语',
      'zh_Hant': '斯洛伐克語',
      'es': 'Eslovaco',
      'fr': 'Slovaque',
      'pt': 'Eslovaco',
      'ru': 'Словацкий',
      'de': 'Slowakisch',
      'ja': 'スロバキア語',
      'it': 'Slovacco',
      'ko': '슬로바키아어',
      'ar': 'السلوفاكية'
    },
    {
      'code': 'sl',
      'en': 'Slovenian',
      'zh_Hans': '斯洛文尼亚语',
      'zh_Hant': '斯洛文尼亞語',
      'es': 'Esloveno',
      'fr': 'Slovène',
      'pt': 'Esloveno',
      'ru': 'Словенский',
      'de': 'Slowenisch',
      'ja': 'スロベニア語',
      'it': 'Sloveno',
      'ko': '슬로베니아어',
      'ar': 'السلوفينية'
    },
    {
      'code': 'sr',
      'en': 'Serbian',
      'zh_Hans': '塞尔维亚语',
      'zh_Hant': '塞爾維亞語',
      'es': 'Serbio',
      'fr': 'Serbe',
      'pt': 'Sérvio',
      'ru': 'Сербский',
      'de': 'Serbisch',
      'ja': 'セルビア語',
      'it': 'Serbo',
      'ko': '세르비아어',
      'ar': 'الصربية'
    },
    {
      'code': 'sv',
      'en': 'Swedish',
      'zh_Hans': '瑞典语',
      'zh_Hant': '瑞典語',
      'es': 'Sueco',
      'fr': 'Suédois',
      'pt': 'Sueco',
      'ru': 'Шведский',
      'de': 'Schwedisch',
      'ja': 'スウェーデン語',
      'it': 'Svedese',
      'ko': '스웨덴어',
      'ar': 'السويدية'
    },
    {
      'code': 'sw',
      'en': 'Swahili',
      'zh_Hans': '斯瓦希里语',
      'zh_Hant': '斯瓦希里語',
      'es': 'Suajili',
      'fr': 'Swahili',
      'pt': 'Suaíli',
      'ru': 'Суахили',
      'de': 'Swahili',
      'ja': 'スワヒリ語',
      'it': 'Swahili',
      'ko': '스와힐리어',
      'ar': 'السواحيلية'
    },
    {
      'code': 'th',
      'en': 'Thai',
      'zh_Hans': '泰语',
      'zh_Hant': '泰語',
      'es': 'Tailandés',
      'fr': 'Thaï',
      'pt': 'Tailandês',
      'ru': 'Тайский',
      'de': 'Thailändisch',
      'ja': 'タイ語',
      'it': 'Thai',
      'ko': '태국어',
      'ar': 'التايلاندية'
    },
    {
      'code': 'tr',
      'en': 'Turkish',
      'zh_Hans': '土耳其语',
      'zh_Hant': '土耳其語',
      'es': 'Turco',
      'fr': 'Turc',
      'pt': 'Turco',
      'ru': 'Турецкий',
      'de': 'Türkisch',
      'ja': 'トルコ語',
      'it': 'Turco',
      'ko': '터키어',
      'ar': 'التركية'
    },
    {
      'code': 'uk',
      'en': 'Ukrainian',
      'zh_Hans': '乌克兰语',
      'zh_Hant': '烏克蘭語',
      'es': 'Ucraniano',
      'fr': 'Ukrainien',
      'pt': 'Ucraniano',
      'ru': 'Украинский',
      'de': 'Ukrainisch',
      'ja': 'ウクライナ語',
      'it': 'Ucraino',
      'ko': '우크라이나어',
      'ar': 'الأوكرانية'
    },
    {
      'code': 'vi',
      'en': 'Vietnamese',
      'zh_Hans': '越南语',
      'zh_Hant': '越南語',
      'es': 'Vietnamita',
      'fr': 'Vietnamien',
      'pt': 'Vietnamita',
      'ru': 'Вьетнамский',
      'de': 'Vietnamesisch',
      'ja': 'ベトナム語',
      'it': 'Vietnamita',
      'ko': '베트남어',
      'ar': 'الفيتنامية'
    },
    {
      'code': 'zh_Hans',
      'en': 'Chinese (Simplified)',
      'zh_Hans': '简体中文',
      'zh_Hant': '簡體中文',
      'es': 'Chino (simplificado)',
      'fr': 'Chinois (simplifié)',
      'pt': 'Chinês (simplificado)',
      'ru': 'Китайский (упрощенный)',
      'de': 'Chinesisch (vereinfacht)',
      'ja': '中国語（簡体字）',
      'it': 'Cinese (semplificato)',
      'ko': '중국어(간체)',
      'ar': 'الصينية (المبسطة)'
    },
    {
      'code': 'zh_Hant',
      'en': 'Chinese (Traditional)',
      'zh_Hans': '繁体中文',
      'zh_Hant': '繁體中文',
      'es': 'Chino (tradicional)',
      'fr': 'Chinois (traditionnel)',
      'pt': 'Chinês (tradicional)',
      'ru': 'Китайский (традиционный)',
      'de': 'Chinesisch (traditionell)',
      'ja': '中国語（繁体字）',
      'it': 'Cinese (tradizionale)',
      'ko': '중국어(번체)',
      'ar': 'الصينية (التقليدية)'
    }
  ]
}

